services:
  # Database: PostgreSQL
  postgres:
    container_name: postgres.dev.local
    image: docker.io/library/postgres:17.5
    environment:
      POSTGRES_DB: discography_db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local-network

  pgadmin:
    container_name: pgadmin.dev.local
    image: docker.io/dpage/pgadmin4:9.5
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin-password
    ports:
      - 8083:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local-network

  # Object Storage: MinIO
  minio:
    container_name: minio.dev.local
    image: docker.io/minio/minio
    environment:
      MINIO_ROOT_USER: minio-admin
      MINIO_ROOT_PASSWORD: minio-admin-password
    ports:
      - "9000:9000" # API
      - "9001:9001" # Admin Console
    volumes:
      - minio-data:/data
    networks:
      - local-network
    command: server /data --console-address ":9001"

  minio-setup:
    container_name: minio-mc.dev.local
    image: docker.io/minio/mc
    depends_on:
      - minio
    entrypoint: /bin/sh
    command: >
      -c "mc alias set local http://minio.dev.local:9000 minio-admin minio-admin-password &&
          mc mb --ignore-existing local/album-covers &&
          mc anonymous set public local/album-covers"
    networks:
      - local-network

volumes:
  postgres-data:
  pgadmin-data:
  minio-data:
networks:
  local-network:
    driver: bridge